kubernetes_version: 1.30
domain_name: "cloudflow.ir"
master1_ip: "116.203.90.121"
master2_ip: "167.235.154.185"
master3_ip: "116.203.241.21"
worker1_ip: "188.245.44.226"
worker2_ip: "167.235.146.42"
master1_name: "master1"
master2_name: "master2"
master3_name: "master3"
vip_api_name: "vip"
vip_ip_address: "vip.cloudflow.ir"
master1_domain: "master1.cloudflow.ir"
master2_domain: "master2.cloudflow.ir"
master3_domain: "master3.cloudflow.ir"
controlplane_endpoint: "vip.cloudflow.ir:6443"
